//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanNavigator.FBIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FBIService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetORI", ReplyAction="http://tempuri.org/IService1/GetORIResponse")]
        string GetORI(string arizonaCity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetORI", ReplyAction="http://tempuri.org/IService1/GetORIResponse")]
        System.Threading.Tasks.Task<string> GetORIAsync(string arizonaCity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FBICrimeData", ReplyAction="http://tempuri.org/IService1/FBICrimeDataResponse")]
        string FBICrimeData(string ori, string offense);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FBICrimeData", ReplyAction="http://tempuri.org/IService1/FBICrimeDataResponse")]
        System.Threading.Tasks.Task<string> FBICrimeDataAsync(string ori, string offense);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UrbanNavigator.FBIService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UrbanNavigator.FBIService.IService1>, UrbanNavigator.FBIService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetORI(string arizonaCity) {
            return base.Channel.GetORI(arizonaCity);
        }
        
        public System.Threading.Tasks.Task<string> GetORIAsync(string arizonaCity) {
            return base.Channel.GetORIAsync(arizonaCity);
        }
        
        public string FBICrimeData(string ori, string offense) {
            return base.Channel.FBICrimeData(ori, offense);
        }
        
        public System.Threading.Tasks.Task<string> FBICrimeDataAsync(string ori, string offense) {
            return base.Channel.FBICrimeDataAsync(ori, offense);
        }
    }
}
